services:
  dovecot:
    image: dovecot/dovecot:latest
    container_name: dovecot
    hostname: dovecot
    restart: unless-stopped
    ports:
      - ${IMAPS_PORT}:993 ## IMAPS port for SSL/TLS connections
      - ${IMAP_STARTTLS_PORT}:143 ## Standard IMAP port for STARTTLS connections
    volumes:
      - ./dovecot.conf:/etc/dovecot/dovecot.conf
      - ${SSL_CERT}:/srv/cert.pem:ro
      - ${SSL_KEY}:/srv/key.pem:ro
      - ${MAIL_VOLUME}:/srv/mail
    environment:
      - TZ
    secrets:
      - dovecot_passwd

  ses-to-lmtp:
    image: coreybraun/ses-to-lmtp
    build:
      context: build/ses-to-lmtp
      additional_contexts:
        common: build/common
    container_name: ses-to-lmtp
    hostname: ses-to-lmtp
    restart: unless-stopped
    depends_on:
      - dovecot
    ports:
      - ${SNS_ENDPOINT_PORT}:443 ## Bind chosen SNS HTTPS endpoint port to container's HTTPS port
    volumes:
      - ${SSL_CERT}:/srv/cert.pem:ro
      - ${SSL_KEY}:/srv/key.pem:ro
    environment:
      - TZ
      - LMTP_ADDRESS=dovecot:24 ## <host>:<port>
      - AWS_CREDENTIALS_FILE=/run/secrets/aws_access_key
      - SNS_CREDENTIALS_FILE=/run/secrets/sns_passwd
      - MAIL_BUCKET
      - DEBUG_MODE
      - DELETE_PROCESSED_EMAILS
      #- DELETE_PROCESSED_EMAILS=true ## Delete processed emails instead of moving them to 'processed/' prefix.
      #- DEBUG_MODE=true ## Output for each message processed, and when script is called but finds no new messages
    secrets:
      - aws_access_key
      - sns_passwd

  postfix-ses-relay:
    image: coreybraun/postfix-ses-relay
    build:
      context: build/postfix-ses-relay
      additional_contexts:
        common: build/common
    container_name: postfix-ses-relay
    hostname: postfix-ses-relay
    restart: unless-stopped
    depends_on:
      - dovecot
    ports:
      - ${SMTP_STARTTLS_PORT}:587 ## Mail submission port for STARTTLS connections
    volumes:
      - ${SSL_CERT}:/srv/cert.pem:ro
      - ${SSL_KEY}:/srv/key.pem:ro
      #- ./custom_login_map:/etc/postfix/custom_login_map ## Mount custom login map
    environment:
      - TZ
      - SASL_ADDRESS=dovecot:12345 ## <host>:<port>
      - AWS_CREDENTIALS_FILE=/run/secrets/aws_access_key
      - AWS_REGION
      - SENDER_DOMAINS
      - WILDCARD_SENDER
      #- SENDER_LOGIN_MAP=pcre:/etc/postfix/custom_login_map ## Use custom login map; If set, SENDER_DOMAINS and WILDCARD_SENDER variables are ignored
    secrets:
      - aws_access_key

volumes:
  nfs-mail-storage:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nfsvers=${NFS_VERSION}"
      device: ":${NFS_PATH}"

secrets:
  dovecot_passwd:
    file: "${SECRETS_PATH}/dovecot_passwd" ## Contents of each line: '<username>:<password>::'
  sns_passwd:
    file: "${SECRETS_PATH}/sns_passwd" ## Contents: '<username>:<password>'
  aws_access_key:
    file: "${SECRETS_PATH}/aws_access_key" ## Contents: '<access_key>:<secret_access_key>'
