AWSTemplateFormatVersion: 2010-09-09
Description: |
  Amazon SES Hybrid-Cloud Email Server Receipt Rule
  https://github.com/corey-braun/hybrid-cloud-email

Parameters:
  UserName:
    Description: The name of the user the receipt rule is for. Messages matching this rule will be stored in S3 under this prefix.
    Type: String
  RecipientConditions:
    Description: List of recipient conditions for this rule.
    Type: CommaDelimitedList
  ScanMail:
    Description: Should emails handled by this user be scanned by SES for viruses and spam? (yes/no)
    Type: String
    Default: 'no'
    AllowedValues: ['yes', 'no']
  StopAction:
    Description: |
      Should the rule set stop being processed after matching this rule? (yes/no)
      If set to "no", messages matching this rule and a later rule will be processed by both, delivering the message to multiple users.
    Type: String
    Default: 'yes'
    AllowedValues: ['yes', 'no']

Conditions:
  ScanIncomingMail: !Equals [!Ref ScanMail, 'yes']
  StopActionAfter: !Equals [!Ref StopAction, 'yes']

Resources:
  SesReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !ImportValue SesMailReceivingRuleSet
      Rule:
        Actions:
          - S3Action:
              BucketName: !ImportValue S3MailStorageBucket
              ObjectKeyPrefix: !Sub "${UserName}/"
              TopicArn: !ImportValue SnsNewMailTopicArn
          - !If
              - StopActionAfter
              - StopAction:
                  Scope: RuleSet
              - !Ref "AWS::NoValue"
        Enabled: true
        Name: !Ref UserName
        Recipients: !Ref RecipientConditions
        ScanEnabled: !If [ScanIncomingMail, true, false]
